steps:
  - label: "Julia 1.5"   # TODO: change this to: label: "Julia 1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.5" # TODO: change this to: version: "1"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      cap: "recent" # this is required because GemmKernels needs a GPU with Tensor Cores
      cuda: "*"
      queue: "juliagpu"
    timeout_in_minutes: 60

  - label: "Julia nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "nightly"
      - JuliaCI/julia-test#v1:
          coverage: false
    agents:
      cap: "recent" # this is required because GemmKernels needs a GPU with Tensor Cores
      cuda: "*"
      queue: "juliagpu"
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  PYTHON: ""           # tells PyCall.jl to install its own Python via Conda.jl
