steps:
  - label: "Julia 1.5"
    plugins:
      - JuliaCI/julia#v0.6:
          version: '1.5'
      - JuliaCI/julia-test#v0.3: ~
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
      cap: "recent"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

  - label: "Julia nightly"
    plugins:
      - JuliaCI/julia#v0.6:
          version: 'nightly'
      - JuliaCI/julia-test#v0.3: ~
      # - JuliaCI/julia-coverage#v0.3:
      #     codecov: true
    agents:
      queue: "juliagpu"
      cuda: "*"
      cap: "recent"
    if: build.message !~ /\[skip tests\]/
    timeout_in_minutes: 60

env:
  JULIA_PKG_SERVER: "" # it often struggles with our large artifacts
  # SECRET_CODECOV_TOKEN: ""
