name: Documentation
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
  workflow_dispatch:
jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            include(joinpath(".ci", "build.jl"))
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()
            Pkg.build()
            Pkg.precompile()'
        env:
          PYTHON: ""
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
          PYTHON: ""
